### PR TITLE
Generate 3D map with label probability image

### PR DESCRIPTION
**Pull request by wkentaro**
The robot is localizing the t-shirts.

image

### CODE REVIEW

**Comment by ahornung** [comment]
Cool!

As this pulls in new dependencies and provides special functionality that may not be needed by everyone, what about putting it in a new, separate package?

**Comment by wkentaro** [comment]
Sounds reasonable, I will do it.

**Comment by wxmerkt** [comment]
Can this be closed @wkentaro?

**Comment by wkentaro** [comment]
Yeah. Sorry, I couldn't make this done.

**Comment by wxmerkt** [comment]
Okay, thank you for the feedback!

**Pull request closed without merging**
